application/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, URL
from flask_ckeditor import CKEditorField



##WTForm
class CreatePostForm(FlaskForm):
    title = StringField("Blog Post Title", validators=[DataRequired()])
    subtitle = StringField("Subtitle", validators=[DataRequired()])
    author = StringField("Author ID", validators=[DataRequired()])
    img_url = StringField("Blog Image URL", validators=[DataRequired(), URL()])
    body = CKEditorField("Blog Content", validators=[DataRequired()])
    submit = SubmitField("Submit Post")


class AddComment(FlaskForm):
    comment = CKEditorField("Your comment", validators=[DataRequired()])
    submit = SubmitField("Add comment")

application/main/routes.py
from flask import render_template, request, Blueprint
from application.models import BlogPost
from application.users.utils import sent_contact_email


main = Blueprint('main', __name__)



@main.route('/', methods=['GET'])
def home():
    print(request.url)
    page_next = request.args.get('page', 1, type=int)
    print("next", page_next)
    #order by date is not working as currently date is a string, needs to bechanged to the DateTime field(re-do the table)
    blogs = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page_next, per_page=3)
    print(blogs.page)
    return render_template("index.html", posts=blogs)

@main.route('/about')
def about_me():
    return render_template("about.html")

@main.route('/contacts',methods=['GET','POST'])
def contacts():
    if request.method == "POST":
        data = [request.form['username'],request.form['email'],request.form['phone'], request.form['message']]
        sent_contact_email(data)
        return render_template("contact.html", message="Successfully sent your message")
    return render_template("contact.html", message="Contact Me")

application/posts/routes.py
from flask import render_template, request, redirect, url_for, flash, Blueprint
from flask_login import current_user
from datetime import datetime
from application import db
from application.models import BlogPost, Comment
from application.posts.forms import AddComment, CreatePostForm
from application.users.utils import admin_only


posts = Blueprint('posts', __name__)

@posts.route('/posts/<num>', methods = ["GET", "POST"])
def get_post(num):
    blog = BlogPost.query.get(int(num))
    form = AddComment()

    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash("You need to login or register to comment.")
            return redirect(url_for("users.login"))
        comment_to_add = Comment(comment = request.form['comment'], author_id = current_user.id, post_id = blog.id)
        db.session.add(comment_to_add)
        db.session.commit()
    return render_template("post.html", post=blog, form=form)


@posts.route('/new-post', methods=["GET", "POST"])
@admin_only
def create_post():
    form = CreatePostForm(author=current_user.id)
    if form.validate_on_submit():
        new_post = BlogPost(title = request.form['title'], subtitle = request.form['subtitle'],
                            date =datetime.today().strftime('%Y-%m-%d'),body=request.form['body'],
                            author= current_user, img_url =request.form['img_url'])
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template("make-post.html", form=form, edit="new")

@posts.route('/edit-post/<num>', methods=["GET", "POST"])
@admin_only
def edit_post(num):
    post_to_edit = BlogPost.query.get(num)
    form = CreatePostForm(title=post_to_edit.title,  subtitle=post_to_edit.subtitle,img_url=post_to_edit.img_url,
                        body=post_to_edit.body)
    if request.method == "POST" and form.validate_on_submit():
        post_to_edit.title = request.form['title']
        post_to_edit.subtitle = request.form['subtitle']
        post_to_edit.body=request.form['body']
        post_to_edit.img_url=request.form['img_url']
        db.session.commit()
        return redirect(url_for('posts.get_post', num=post_to_edit.id))
    return render_template("make-post.html", form=form, edit="not new", post_id=post_to_edit.id)

@posts.route('/delete-post/<num>', methods=["GET", "POST"])
def delete_post(num):
    post_to_delete = BlogPost.query.get(num)
    db.session.delete(post_to_delete)
    db.session.commit()
    return redirect(url_for('main.home'))

application/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy.exc import IntegrityError
from application import db
from application.models import User, BlogPost
from application.users.forms import LoginForm, RegisterForm, RequestResetForm, ResetPasswordForm
from application.users.utils import send_reset_email
from werkzeug.security import generate_password_hash, check_password_hash

users = Blueprint('users', __name__)

@users.route('/login', methods = ["GET", "POST"])
def login():
    form = LoginForm()
    # if current_user.is_authenticated:
    #     return redirect(url_for('home'))
    # # print("first:",[arg for arg in request.args])
    next_page = request.args.get('next')
    #
    if request.method == "POST" :
        user_email = request.form.get('email')
        user = User.query.filter_by(email=user_email).first()
        if not user:
            flash("That email does not exist, please try again.")
        if user and check_password_hash(user.password, request.form.get('password')):
            login_user(user)
            print(current_user.id)
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash('Login unsuccessful. Please check password and try again.')
    return render_template("login.html", form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/register', methods = ["GET", "POST"])
def register():
    form = RegisterForm()
    # if current_user.is_authenticated:
    #     return redirect(url_for('main.home'))
    if form.validate_on_submit():
        hashed_password = generate_password_hash(request.form.get('password'), method='pbkdf2:sha256',salt_length=8)
        new_user = User (email = request.form['email'],password = hashed_password,name= request.form['name'] )
        try:
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for('main.home'))
        except IntegrityError:
            flash("User with this email already exists. Please log in",'warning')
            return redirect(url_for('users.login'))
    return render_template("register.html", form=form)


@users.route('/reset-password', methods = ["GET", "POST"])
def reset_password():
    form = RequestResetForm()
    # if current_user.is_authenticated:
    #     return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been send with instructions")
        return redirect(url_for("users.login"))
    return render_template("request_reset.html", form=form)

@users.route('/reset-password/<secret>', methods = ["GET", "POST"])
def reset_token(secret):
    print(secret)
    # if current_user.is_authenticated:
    #     return redirect(url_for('home'))
    user = User.verify_reset_token(token=secret)
    if user is None:
        flash('This link has expired')
        return redirect(url_for("users.reset_password"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(request.form.get('password'), method='pbkdf2:sha256', salt_length=8)
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated", 'warning')
        return redirect(url_for('users.login'))
    return render_template("request_reset.html", form=form)

application/templates/about.html
 {% include'header.html' %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('static/assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
 {% include 'footer.html' %}

application/templates/contact.html
{% include'header.html' %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('static/assets/img/contact-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>{{ message }}</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form name="sentMessage "id="contactForm" action="{{ url_for('main.contacts') }}" method="post" novalidate>
                                <div class="form-floating">
                                    <input class="form-control" id="name" type="text" name="username" placeholder="Enter your name..." data-sb-validations="required" />
                                    <label for="name">Name</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="email" type="email" name="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                    <label for="email">Email address</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="phone" type="tel" name="phone" placeholder="Enter your phone number..." data-sb-validations="required" />
                                    <label for="phone">Phone Number</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" id="message" name="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                    <label for="message">Message</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                </div>
                                <br />
                               

                                <!-- Submit Button-->
                                <button class="btn btn-primary" id="submitButton" type="submit" value="Submit">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        {% include 'footer.html' %}

application/templates/footer.html
<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
            </div>
        </div>
    </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    </body>
</html>

application/templates/header.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='assets/favicon.ico') }}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{{ url_for('main.home') }}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('main.home') }}">Home</a></li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('users.logout') }}">Log Out</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('users.login') }}">Login</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('users.register') }}">Register</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('main.about_me') }}">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{ url_for('main.contacts') }}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

application/templates/index.html
{% include'header.html' %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('static/assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Darja's random Blog</h1>
                            <span class="subheading">A collection of random stuff</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for post in posts.items  %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{{ url_for('posts.get_post', num=post['id']) }}">
                            <h2 class="post-title">{{ post['title']}} </h2>
                            <h3 class="post-subtitle">{{ post['subtitle'] }}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">{{ post.author.name }}</a>
                            on {{ post.date }}
                        {% if current_user.id == 1 %}
                            <a href="{{ url_for('posts.delete_post', num=post.id) }}"> ✘ </a>
                            {% endif %}
                        </p>

                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}

                            <!-- Pager-->
                    {% if posts.page < posts.pages %}
                        <div class="d-flex float-right mb-4"><a class="btn btn-primary text-uppercase" href="{{ url_for('main.home', page=(posts.page+1)) }}">Older Posts →</a></div>
                    {% else %}
                    You've reached the end of blog
                        <div class="d-flex float-right mb-4"><a class="btn btn-primary text-uppercase" href="{{ url_for('main.home', page=(posts.page-1)) }}">Newer Posts →</a></div>
                    {% endif %}
                     <!-- New Post -->
                    {% if current_user.id == 1 %}
                    <div class="clearfix">
                      <a class="btn btn-primary justify-content-end mb-4" href="{{url_for('posts.create_post')}}">Create New Post</a>
                    </div>

                    {% endif %}

                    <!-- Pager-->
<!--                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>-->
                </div>
            </div>
        </div>
        {% include 'footer.html' %}

application/templates/login.html
{% import "bootstrap/wtf.html" as wtf %}
{% include "header.html" %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1484100356142-db6ab6244067?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Log In</h1>
            <span class="subheading">Welcome Back!</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="row">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
         <p class="alert alert-warning">{{ message }}</p>
        {% endfor %}
      {% endif %}
      {% endwith %}
      {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
       <small class="text-muted" style="margin-left: 15%; margin-top:3%">
          <a href="{{ url_for('users.reset_password') }}">Forgot password?</a>
       </small>
    </div>
  </div>
</div>
<div >
</div>

{% include "footer.html" %}
<div class="col-lg-8 col-md-10 mx-auto content">

application/templates/make-post.html
{% include "header.html" %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{url_for('static', filename='assets/img/edit-bg.jpg')}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
			  {% if edit=="new" %}
            <h1>New Post</h1>
            <span class="subheading">You're going to make a great blog post!</span>
			  {% else %}
            <h1>Edit post</h1>
            <span class="subheading">You can edit your post here!</span>
			  {% endif %}
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
         {% if edit=="new" %}
         <form method=post action="{{url_for('posts.create_post')}}" >
			 {% else %}
			 <form method=post action="{{url_for('posts.edit_post', num=post_id) }}" >
				 {% endif %}
		  <dl>
			  {{ form.csrf_token }}
			  <p>
			{{ form.title.label}} <br> {{form.title(size=30) }}
				{% for err in form.title.errors %}
				  <span style="color:red"> {{err}} </span>
				  {% endfor %}
			  </p>
			  <p>
			{{ (form.subtitle.label) }} <br> {{form.subtitle(size=50) }}
			{% for err in form.subtitle.errors %}
				  <span style="color:red"> {{err}} </span>
				  {% endfor %}
			  </p>
			  <p>
			{{ (form.body.label) }} <br> {{form.body(size=50) }}
				  {% for err in form.body.errors %}
				  <span style="color:red"> {{err}} </span>
				  {% endfor %}
			  </p>
			   <p>
			{{ (form.img_url.label) }} <br> {{form.img_url }}
				   {% for err in form.img_url.errors %}
				  <span style="color:red"> {{err}} </span>
				  {% endfor %}
			  </p>
			   <p>
<!--				   <input class="btn btn-primary float-right" id="submit" name="submit" type="submit" ></input>-->
				{{form.submit(class_="btn btn-primary float-right") }}
			  </p>
			</dl>
          </form>
		  {{ ckeditor.load() }}
         {{ ckeditor.config(name='body') }}

      </div>
    </div>
  </div>

{% include "footer.html" %}

application/templates/post.html
{% import "bootstrap/wtf.html" as wtf %}
{% include "header.html" %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{post.img_url}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{ post['title']}}</h1>
                            <h2 class="subheading">{{ post['subtitle'] }}</h2>
                            <span class="meta">
                                Posted by
                                <a href="#">{{post.author.name}}<a>
                                on {{post.date}}</span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        
                        <p>{{ post.body|safe }}</p>

                        </p>
                           <hr>
                        <div class="col-lg-8 col-md-10 mx-auto comment">

                            <ul class="commentList">
                                {% for comment in post.comments %}
                                <li>
                                    <div class="commenterImage">
                                        <img src="{{ comment.comment_author.email | gravatar }}" alt="icon-user" width="32" height="32">
                                    </div>
                                    <div class="commentText">
                                        {{ comment.comment|safe  }}
                                        <span class="date sub-text">{{ comment.comment_author.name }} </span>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>

                        </div>
                        <hr>
                         {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}

                        </p>
                        {{ ckeditor.load() }}
                        {{ ckeditor.config(name='comment') }}

                        {% if current_user.id == 1 %}
                       <div class="clearfix">
                      <a class="btn btn-primary float-right mt-5" href="{{url_for('posts.edit_post', num=post.id)}}">Edit Post</a>
                    </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </article>
      <!-- Footer-->
{% include "footer.html" %}

application/templates/register.html
{% import "bootstrap/wtf.html" as wtf %}

{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1531592937781-344ad608fabf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Register</h1>
            <span class="subheading">Start Contributing to the Blog!</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
         <p calss="alert alert-{{category}}">{{ message }}</p>
        {% endfor %}
      {% endif %}
    {% endwith %}
       
       {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}

      </div>
    </div>
  </div>

{% include "footer.html" %}

application/templates/request_reset.html
{% import "bootstrap/wtf.html" as wtf %}
{% include "header.html" %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1484100356142-db6ab6244067?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Reset your password</h1>
            <span class="subheading"></span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <div class="row">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
         <p class="alert alert-warning">{{ message }}</p>
        {% endfor %}
      {% endif %}
      {% endwith %}
      {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
    </div>
  </div>
</div>
<div >
</div>

{% include "footer.html" %}
<div class="col-lg-8 col-md-10 mx-auto content">